### ISSUE TITLE
ModuleNotFoundError: No module named 'RPi'

### ISSUE THREAD

**Issue by sajmons** [Gordon999/Pi-LC-Autoguider#1]
When I start PiLCAG with terminal command 
`python3 PiLCAG.py `
I get this:

```
Still capture image received
    import RPi.GPIO as GPIO
ModuleNotFoundError: No module named 'RPi'
```

I instaled rpi.gpio with sudo apt-get install rpi.gpio and then I got this:

```
Traceback (most recent call last):
  File "/home/stellarmate/Downloads/./PiLCAG.py", line 452, in <module>
    GPIO.setup(C_OP, GPIO.OUT)
RuntimeError: Not running on a RPi!
Still capture image received

```

What Am I doing wrong? PiLibCameraGUI.py works flawlessly.

When I run it with
`sudo python3 PiLCAG.py`
then it works.

**Comment by Gordon999** [comment]
What OS are you using? I use the FULL 32bit or 64 bit RaspiOS. RPi.GPIO should be there by default

**Comment by sajmons** [comment]
I'm using Stellarmate 64 bit that is based on bullseye.

**Comment by Gordon999** [comment]
Sorry l haven't come across this before but reading you may need to build RPi.GPIO manually.

This may help  https://www.raspberrypi-spy.co.uk/2012/05/install-rpi-gpio-python-library/

**Comment by Gordon999** [comment]
Assumed fixed
