### ISSUE TITLE
Pi-LC-Autoguider for Rocket Launches?

### ISSUE THREAD

**Issue by JohnRSmith101** [Gordon999/Pi-LC-Autoguider#2]
Can this code be adapted to support tracking boosting rockets?  Rocket launches out of Cape Canaveral/Kennedy Space Center as seen from my location 140 miles away have angular motion up to about 30x the sidereal rate, in any direction.  My EQ6R-Pro GoTo mount can rotate this fast, but can Pi-LC-Autoguider command the mount via its ST-4 port to track such an object?  

Attached are a wide angle time exposure, and a frame extracted from video through my telescope for context.

![20220427 SpaceX to ISS](https://user-images.githubusercontent.com/85898866/204371856-bb45c2af-eaca-4509-b225-3450bcb657ce.jpg)
![StarlinkLaunchFrame](https://user-images.githubusercontent.com/85898866/204372031-56bfb627-5367-478b-83fa-885ee167a4e6.jpg)

**Comment by Gordon999** [comment]
I don't think so. I don't think it will track fast enough

**Comment by JohnRSmith101** [comment]
Thank-you for responding.

I’m currently doing the tracking using a numeric keypad and EKOS/Indi connected through the mount’s RJ45 port , but it’s not a very good approach.  I’m hoping to find a better solution.

Thanks also for your great work and write-ups with RPi.  I’ve struggled, whereas you have provided some excellent code that I will find useful.  Some of the best I’ve seen.

Best Regards,
John

**Comment by Gordon999** [comment]
Thankyou for your comments. The software finds the centre of a  star, or bright object, and sends commands to move the telescope to follow it. If it can identify the rocket , which maybe an issue looking at the image you posted, it maybe able to follow it. Might be worth a try depending on the telescope slew rate.

All the best.

**Comment by Gordon999** [comment]
Closed
